{
 "title": "Command Monitoring",
 "description": "Monitor Bash commands executed on the server and inside Docker containers",
 "tags": [ "Docker" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Container",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{image!=\"\"})"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(container_last_seen{image!=\"\"})"
    }
   ]
  },
  {
   "title": "Current Active User ",
   "type": "table",
   "gridPos": { "h": 16, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "rule.id:100201",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "rule.id:100202",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule.id:100202",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Bash Commands",
   "type": "table",
   "gridPos": { "h": 31, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "rule.id:100401 -location:journald",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}