{
 "title": "System Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Server Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 5, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "options": { "reduceOptions": { "calcs": [ "first" ] } },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "rule.id:100100",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Memory Used",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 8, "x": 5, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "GB" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "rule.id:100105",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Total Memory",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 13, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "rule.id:100105",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 9, "x": 15, "y": 1 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "1000" }, "type": "raw_data" }
       ],
       "query": "rule.id:100104",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Disk Space Used ",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 8, "x": 5, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "100106",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Total Disk Space",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 13, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "rule.id:100106",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "System Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "1500" }, "type": "raw_data" }
       ],
       "query": "rule.id:100100",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "User",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Active Users",
     "type": "stat",
     "gridPos": { "h": 10, "w": 5, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "first" ] } },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "rule.id:100202",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Current Active User ",
     "type": "table",
     "gridPos": { "h": 10, "w": 10, "x": 5, "y": 2 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "rule.id:100201",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "SSH: Login Warnings",
     "type": "barchart",
     "description": "SSH Logins per 5min",
     "gridPos": { "h": 10, "w": 9, "x": 15, "y": 2 },
     "targets": [
      {
       "alias": "Authentication Success",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "rule.id:5715",
       "timeField": "@timestamp"
      },
      {
       "alias": "Authentication Failed",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "rule.id:[5700 TO 5761] AND NOT rule.id:5715",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Bash Commands",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "rule.id:100401 -location:journald",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Sudo Bash Commands",
     "type": "table",
     "description": "Only commands executed by the super user",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
       ],
       "query": "rule.id:5402",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Package Flow",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "heiDPId Flow Events",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 378 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
       ],
       "query": "rule.id:100501 ",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "heiDPI Packet Events",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 386 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "rule.id:100502",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Packet  Events per minute",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 386 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "rule.id:100502",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Flow Events per minute",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 15, "x": 0, "y": 393 },
     "targets": [
      {
       "alias": "Uni Heidelberg Flow Events",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "rule.id:100501 AND data.dst_ip:129.206.100.126",
       "timeField": "@timestamp"
      },
      {
       "alias": "Internal Flow Events",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "rule.id:100501 AND data.dst_ip:10* AND (data.src_ip:10.20.30.60)",
       "timeField": "@timestamp"
      },
      {
       "alias": "External Flow Events",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "rule.id:100501 AND NOT data.dst_ip:10* AND NOT (data.dst_ip:255.* OR data.dst_ip:ff0.*) AND NOT data.dst_ip:129.206.100.126 AND (data.src_ip:10.20.30.60)",
       "timeField": "@timestamp"
      },
      {
       "alias": "Broadcast",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "rule.id:100501 AND (data.dst_ip:255.* OR data.dst_ip:ff0.*) AND (data.src_ip:10.20.30.60)",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "External IPs",
     "type": "table",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 393 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "rule.id:100501 AND NOT data.dst_ip:10\\.* AND NOT data.dst_ip:ff0* AND NOT data.dst_ip:255* AND data.ndpi.hostname:[* TO *] AND NOT data.dst_ip:129.206.100.126",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "External IPs w/o Hostname",
     "type": "table",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 401 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "rule.id:100501 AND NOT data.dst_ip:10\\.* AND NOT data.dst_ip:ff0* AND NOT data.dst_ip:255* AND NOT data.ndpi.hostname:[* TO *] AND NOT data.dst_ip:129.206.100.126",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "heiDPId Incomming Flow Events",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 15, "x": 0, "y": 409 },
     "targets": [
      {
       "alias": "Internal Unicast",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "rule.id:100501 AND NOT (data.src_ip:10.20.30.60) AND NOT (data.dst_ip:255.* OR data.dst_ip:ff0.*) AND data.src_ip:10.*",
       "timeField": "@timestamp"
      },
      {
       "alias": "Broadcast",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "rule.id:100501 AND NOT (data.src_ip:10.20.30.60) AND (data.dst_ip:255.* OR data.dst_ip:ff0.*)",
       "timeField": "@timestamp"
      },
      {
       "alias": "External Unicast",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "rule.id:100501 AND NOT (data.src_ip:10.20.30.60) AND NOT (data.dst_ip:255.* OR data.dst_ip:ff0.*) AND NOT data.src_ip:10.*",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "heiDPId Incomming Flow Events",
     "type": "table",
     "gridPos": { "h": 11, "w": 9, "x": 15, "y": 409 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
       ],
       "query": "rule.id:100501 AND NOT (data.src_ip:10.20.30.60)",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Uni Heidelberg IPs",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 420 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "rule.id:100501 AND (data.dst_ip:129.206.100.126 OR data.dst_ip:129.206.100.127)",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Firewall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "UFW Events",
     "type": "table",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 776 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
       ],
       "query": "rule.id:100601",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "UFW Port Status",
     "type": "table",
     "gridPos": { "h": 21, "w": 9, "x": 15, "y": 776 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "rule.id:100600 AND data.Action:*",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Firewall Block events",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 15, "x": 0, "y": 784 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "rule.id:100601",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Blocked IPs",
     "type": "table",
     "gridPos": { "h": 6, "w": 15, "x": 0, "y": 791 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "rule.id:100601",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Foreign Flow",
     "type": "geomap",
     "gridPos": { "h": 30, "w": 24, "x": 0, "y": 183 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "rule.id:100501 AND longitude AND NOT data.dst_ip:129.206.100.126",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}