{
 "title": "Wazuh",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Wazuh Server Health",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "rule.id:100054",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "UFW Port Status",
   "type": "table",
   "gridPos": { "h": 26, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "rule.id:100301",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Current Active Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "rule.id:100102",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Current Active User ",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 10 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "rule.id:100101\n",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SSH: Login Warnings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 10 },
   "targets": [
    {
     "alias": "    authentication_success",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule.id:5501",
     "timeField": "@timestamp"
    },
    {
     "alias": "Non-existent user",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule.id:5710",
     "timeField": "@timestamp"
    },
    {
     "alias": "Brute force trying",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule.id:5712",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Bash Commands",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 18 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "rule.id:100201 -location:journald",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "heiDPI Packet Events",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "rule.id:100012",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "heiDPId Flow Events",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "rule.id:100011",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Bash Log",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "rule.id:5402",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "UFW Events",
   "type": "table",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 61 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "rule.id:104102",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "geomap",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "rule.id:100011 AND longitude",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}