services:
    heidpi-producer:
        container_name: heiDPI_producer
        volumes:
            - var_log:/var/log
            - tmp:/tmp
        restart: unless-stopped
        network_mode: host
        image: stefan96/heidpi-producer:main
        entrypoint: ["/bin/bash","-c", "rm -f /tmp/nDPIsrvd-daemon-distributor.sock && rm -f /tmp/nDPIsrvd-daemon-collector.sock && /root/docker-entrypoint.sh && nDPId"]
    heidpi-consumer:
        container_name: heiDPI_consumer
        environment:
            - SHOW_ERROR_EVENTS=1
            - SHOW_DAEMON_EVENTS=1
            - SHOW_PACKET_EVENTS=1
            - SHOW_FLOW_EVENTS=1
            - HOST=127.0.0.1
        volumes:
            - var_log:/var/log
            - tmp:/tmp
            - <config_absolute_path>:/usr/src/app/config.yml
            - /var/lib/GeoLite2/city.mmdb:/tmp/city.mmdb
        restart: unless-stopped
        network_mode: host
        image: stefan96/heidpi-consumer:main

volumes:
    var_log:
    tmp:
